theme: minima 
title: Joseph Curto's Resume Site
author: Joseph Curto
email: joey.curto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is to showcase some of the coding projects I have completed and some 
  that I am currently working on in school or on my own.

# social links
github_username:  josephCurto

show_excerpts: true # set to false to remove excerpts on the homepage
